services:
  - type: web
    name: logmath-backend
    runtime: docker
    dockerfilePath: ./src/BackEnd/Dockerfile
    dockerContext: ./
    region: ohio
    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logmath_db
          property: connectionString
      - key: ENVIRONMENT
        value: production

databases:
  - name: logmath_db
    databaseName: logmath_db
    user: logmath_user
    region: ohio