name: backend ci and deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'src/BackEnd/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/BackEnd/**'

permissions:
  contents: write

jobs:
  # Backend CI
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set-up python  
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'
 
      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install -r src/BackEnd/requirements-dev.txt

      - name: Run Backend Tests
        run: |
          if [ -n "$(find src/BackEnd/tests -name 'test_*.py' -o -name '*_test.py')" ]; then
            pytest src/BackEnd/tests
          else
            echo "⚠️ No tests found, skip"
          fi

      - name: Run flake8 (sintaxis)
        run: flake8 src/BackEnd

      - name: Run bandit (seguridad)
        run: bandit -r src/BackEnd

  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Deploy to Render
        env:
          WEBHOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$WEBHOOK_URL"

      - name: Deployment Summary
        run: |
          echo "Deploy iniciado en Render"
  