name: build-apk
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 
      # Descarga el codigo
      - name: Checkout code
        uses: actions/checkout@v4.1.0
 

      # Configura python
      - name: Set-up python  
        uses: actions/setup-python@v5
        with: 
          python-version: '3.14.4'
 
      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install flet

      #se usa porq flet usa fluter     
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Build APK
        run: |
          cd src/FrontEnd
          flet build apk

          ls -lah build/apk/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: logimath-apk

          path: src/FrontEnd/build/apk/*.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:

          files: src/FrontEnd/build/apk/*.apk

          tag_name: v${{ github.run_number }}
          name: "LogiMath Build #${{ github.run_number }}"

          body: |
            🚀 APK compilado automáticamente

            📱 Cómo instalar:
            1. Descarga el APK abajo
            2. Transfiere a tu Android
            3. Abre el APK → Install

            Backend: https://logimathapp.onrender.com

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Summary
        run: |
          echo "✅ APK compilado: v${{ github.run_number }}"
          echo "🔗 https://github.com/${{ github.repository }}/releases"